# This is a basic workflow to help you get started with Actions

name: Create Project Card from Proposal Issues

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  issues:
    types:
      - opened

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  add-to-project:
    name: Add Issue to GitHub projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/users/nickdelgrosso/projects/3
          github-token: ${{ secrets.ISSUE_ADD }}
          
